# Generated by Django 5.0.3 on 2024-04-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyboardBuilder',
            fields=[
                ('keyboard_builder_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyboard_assembly', models.IntegerField()),
            ],
            options={
                'db_table': 'keyboard_builder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyboardBuilderItem',
            fields=[
                ('keyboard_builder_item_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'keyboard_builder_item',
                'managed': False,
            },
        ),
    ]
