# Generated by Django 5.0.3 on 2024-04-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('order_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'order_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('order_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
