# Generated by Django 5.0.3 on 2024-04-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('item_quantity', models.IntegerField()),
                ('restock_point', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemProperty',
            fields=[
                ('item_property_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_property_name', models.CharField(max_length=255, unique=True)),
                ('item_property_datatype', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'item_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPropertyValue',
            fields=[
                ('item_property_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_property_value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'item_property_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('item_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'item_type',
                'managed': False,
            },
        ),
    ]
