# Generated by Django 5.0.3 on 2024-04-14 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('item_quantity', models.IntegerField()),
                ('restock_point', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemProperty',
            fields=[
                ('item_property_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_property_name', models.CharField(max_length=255, unique=True)),
                ('item_property_datatype', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'item_property',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('item_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'item_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KeyboardBuilder',
            fields=[
                ('keyboard_builder_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyboard_assembly', models.IntegerField()),
            ],
            options={
                'db_table': 'keyboard_builder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('order_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemPropertyValue',
            fields=[
                ('item_property_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_property_value', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.item')),
                ('item_property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.itemproperty')),
            ],
            options={
                'db_table': 'item_property_value',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.itemtype'),
        ),
        migrations.CreateModel(
            name='KeyboardBuilderItem',
            fields=[
                ('keyboard_builder_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.item')),
                ('keyboard_builder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.keyboardbuilder')),
            ],
            options={
                'db_table': 'keyboard_builder_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('order_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.orders')),
            ],
            options={
                'db_table': 'order_line',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=11, null=True)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.userprofile')),
            ],
            options={
                'db_table': 'user_address',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='keyboardbuilder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.userprofile'),
        ),
    ]
