# Generated by Django 5.0.3 on 2024-04-15 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('item_brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_brand_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'item_brand',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemProperty',
            fields=[
                ('item_property_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_property_name', models.CharField(max_length=255, unique=True)),
                ('item_property_datatype', models.CharField(help_text='Valid values: string, integer, decimal, boolean', max_length=255)),
            ],
            options={
                'db_table': 'item_property',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemPropertyValue',
            fields=[
                ('item_property_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_property_value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'item_property_value',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('item_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'item_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KeyboardBuilder',
            fields=[
                ('keyboard_builder_id', models.AutoField(primary_key=True, serialize=False)),
                ('self_assembly', models.BooleanField()),
            ],
            options={
                'db_table': 'keyboard_builder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KeyboardBuilderItem',
            fields=[
                ('keyboard_builder_item_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'keyboard_builder_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('order_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'order_line',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(help_text='Valid values: pending, processing, shipped', max_length=255)),
                ('payment_status', models.CharField(help_text='Valid values: pending, paid, failed, refunded', max_length=255)),
                ('order_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=11, null=True)),
                ('profile_picture_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('item_profile_picture_link', models.TextField(blank=True, null=True)),
                ('item_quantity', models.IntegerField()),
                ('restock_point', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('item_brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.itembrand')),
            ],
            options={
                'db_table': 'item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemPicture',
            fields=[
                ('item_picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.item')),
            ],
            options={
                'db_table': 'item_picture',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='itemproperty',
            constraint=models.CheckConstraint(check=models.Q(('item_property_datatype__in', ['string', 'integer', 'decimal', 'boolean'])), name='valid_item_property_datatype'),
        ),
        migrations.AddField(
            model_name='itempropertyvalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.item'),
        ),
        migrations.AddField(
            model_name='itempropertyvalue',
            name='item_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.itemproperty'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.itemtype'),
        ),
        migrations.AddField(
            model_name='keyboardbuilderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.item'),
        ),
        migrations.AddField(
            model_name='keyboardbuilderitem',
            name='keyboard_builder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.keyboardbuilder'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.item'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.orders'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='keyboardbuilder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='orders',
            constraint=models.CheckConstraint(check=models.Q(('order_status__in', ['pending', 'processing', 'shipped'])), name='valid_order_status'),
        ),
        migrations.AddConstraint(
            model_name='orders',
            constraint=models.CheckConstraint(check=models.Q(('payment_status__in', ['pending', 'paid', 'failed', 'refunded'])), name='valid_payment_status'),
        ),
    ]
